### ISSUE TITLE
(Simple) usage example?

### ISSUE THREAD

**Issue by potherca** [Ariadne-CMS/arc-config#8]
For a new project I am looking for a configuration loader. The [Symfony Config Component](http://symfony.com/doc/current/components/config/resources.html) seems rather verbose so I though about maybe using ARC config...

Only, there doesn't seem to be even the most basic usage example :crying_cat_face:

**Comment by poef** [comment]
I've added documentation with some example code, hope that helps. Please note that \arc\config has a very limited scope, so it doesn't know how to parse Yaml, JSON or XML and it has no idea of filesystems. This means it will not be a plugin replacement for the Symfone Config Component.
